# Generated by Django 4.2.25 on 2025-10-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
