# Generated by Django 4.2.25 on 2025-10-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_is_activate_cart_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
